import random 


Antioquia=["Abejorral","Abriaquí","Alejandría","Amagá","Amalfi","Andes","Angelópolis","Angostura","Anorí","Anzá","Apartadó","Arboletes","Argelia","Armenia","Barbosa","Bello","Belmira","Betania","Betulia","Briceño","Buritcá","Caicedo","Caldas","Campamento","Caracolí","Caramanta","Carepa","Carolina del Príncipe","Caucasia","Cañasgordas","Chigorodó","Cisneros","Ciudad Bolivar","Cocomá","Concepción","Concordia","Copacabana","Cáceres","Dabeiba","Donmatías","Ebéjico","El Bagre","El Carmen de Viboral","El Peñol","El Retio","El Santuario","Entrerríos","Envigado","Fredonia","Frontino","Giraldo","Girardota","Granada","Guadalupe","Guarne","Guatapé","Gómez Plata","Heliconia","Hispania","Itagüí","Ituango","Jardín","Jericó","La Ceja","La Estrella","La Pintada","La Unión","Liborina","Maceo","Marinilla","Medellín","Montebello","Murindó","Mutatá","Nechí","Necoclí","Olaya","Peque","Pueblorrico","Puerto Berrío","Puerto Nare","Puerto Triunfo","Remedios","Rionegro","Sabanalarga","Sabaneta","Salgar","San Andrés de Cuerquia","San Carlos","San Francisco","San Jerónimo","San José de la Montaña","San Juan de Urabá","San Luis","San Pedro de los Milagros","San Pedro de Urabá","San Rafael","San Rogue","San Vicente","Santa Bárbara","Santa Fe de Antioquia","Santa Rosa de Osos","Santo Domingo","Segovia","Sonsón","Sopetrán","Tarazá","Tarso","Titiribí","Toledo","Turbo","Támesis","Uramita","Urrao","Valdivia","Valparaíso","Vegachí","Venecia","Vigía del Fuerte","Yalí","Yarumal","Yolombó","Yondó","Zaragoza"]
Amazonas=["El Ecanto","La Chorrera","La Pedrera","La Victoria","Leticia","Mirití-Paraná","Puerto Alegría","Puerto Arica","Puerto Nariño","Puerto Santander","Tarapacá"]
Arauca=["Arauca","Arauquita","Cravo Norte","Fortul","Puerto Rondón","Saravena","Tame"]
Atlantico=["Baranoa","Barranquilla","Campo de la Cruz","Candelaria","Galapa","Juan de Acosta","Luruaco","Malambo","Manatí","Palmar de Varela","Piojó","Polonuevo","Ponedera","Puerto Colombia","Repelón","Sabanalarga","Sanagrande","Santa Lucía","Santo Tomás","Soledad","Suan","Tubará","Usiacurí"]
Bolivar=["Achí","Altos del Rosario" ,"Arenal","Arenal" ,"Arjona" ,"Arroyohondo" ,"Barranco de Loba","Calamar" ,"Cantagallo" ,"Cartagena de Indias","Cicuco","Clemencia","Córdoba","El Carmen de Bolívar" ,"El Guamo","El Peñón","Hatillo de Loba" ,"Magangué" ,"Mahates" ,"Margarita" ,"María La Baja" ,"Montecristo","Morales" ,"Norosí" ,"Pinillos","Puerto Rico","Río Viejo","San Cristóbal","San Fernando","San Jacinto","San Jacinto del Cauca","San Juan Nepomuceno","San Martín de Loba","San Pablo","Santa Catalina","Santa Cruz de Mompox","Santa Rosa","Santa Rosa del Sur","Simití","Soplaviento","Talaigua Nuevo","Turbaco","Turbaná","Villanueva","Zambrano"]
Boyaca=["Chíquiza","Chivatá","Cómbita"	,"Cucaita","Motavita","Oicatá","Samacá","Siachoque","Sora","Soracá","Sotaquirá","Toca","Tunja","Tuta","Ventaquemada","Chiscas","El Cocuy","El Espino","Guacamayas","Güicán","Panqueba","Labranzagrande","Pajarito","Paya","Pisba","Berbeo","Campohermoso","Miraflores","Páez","San Eduardo","Zetaquira","Boyacá","Ciénega","Jenesano","Nuevo Colón","Ramiriquí","Rondón","Tibaná","Turmequé","Úmbita","Viracachá","Chinavita","Garagoa","Macanal","Pachavita","San Luis de Gaceno","Santa María","Boavita","Covarachía","La Uvita","San Mateo","Sativanorte","Sativasur","Soatá","Susacón","Tipacoque","Briceño","Buenavista","Caldas","Chiquinquirá","Coper","La Victoria","Maripí","Muzo","Otanche","Pauna","Quípama","Saboyá","San Miguel de Sema","San Pablo de Borbur","Tununguá","Almeida","Chivor","Guateque","Guayatá","La Capilla","Somondoco","Sutatenza","Tenza","Arcabuco","Chitaraque","Gachantivá","Moniquirá","Ráquira","Sáchica","San José de Pare","Santa Sofía","Santana","Sutamarchán","Tinjacá","Togüí","Villa de Leyva","Aquitania","Cuítiva","Firavitoba","Gámeza","Iza","Mongua","Monguí","Nobsa","Pesca","Sogamoso","Tibasosa","Tópag","Tota","Belén","Busbanzá","Cerinza","Corrales","Duitama","Floresta","Paipa","Santa Rosa de Viterbo","Tutazá","Betéitiva","Chita","Jericó","Paz de Río","Socha","Socotá","Tasco","Cubará","Puerto Boyacá"]
Caldas=["Aguadas","Anserma" ,"Aranzazu","Belalcázar","Chinchiná" ,"Filadelfia","La Dorada" ,"La Merced","Manizales","Manzanares","Marmato","Marquetalia","Marulanda" ,"Neira" ,"Norcasia","Palestina","Pensilvania","Pácora" ,"Riosucio" ,"Risaralda" ,"Salamina","Samaná" ,"San José" ,"Supía" ,"Victoria","Villamaría" ,"Viterbo" ]
Caqueta=["Albania","Belén de los Andaquíes","Cartagena del Chaira","Curillo","Doncello","Paujíl","Florencia","La Montañita","Milán","Morelia","Puerto Rico","San José del Fragua","San Vicente del Caguan","Solano","Solita","Valparaiso"]
Casanare=["Aguazul","Chámeza","Hato Corozal","La Salina","Maní","Monterrey","Nunchía","Orocué","Paz de Ariporo","Pore","Recetor","Sabanalarga","San Luis de Palenque","Sácama","Tauramena","Trinidad","Támara","Villanueva","Yopal"]
Cauca=["Almaguer","Argelia","Balboa","Bolívar","Buenos Aires","Caldono","Caloto","Corinto","El Tambo","Florencia","Guachené","Guapi","Inzá","Jambaló","La Sierra","La Vega","López de Micay","Mercaderes","Miranda","Morales","Padilla","Patía","Piamonte","Piendamó","Popayán","Puerto Tejada","Puracé-Coconuco","Páez","Rosas","San Sebastían","Santa Rosa","Santander de Quilichao","Silvia","Soltará","Sucre","Suárez","Timbiquí","Timbío","Toribío","Totoró","Villa Rica"]
Cesar=["Aguachica","Agustín Codazzi","Astrea","Becerril","Bosconia","Chimichagua","Chiriguaná","Curumaní","El Copey","El Paso","Gamarra","González","La Gloria","La Jagua de Ibirico","La Paz","Manaure","Pailitas","Pelaya","Pueblo Bello","Río de Oro","San Alberto","San Diego","San Martín","Tamalameque","Valledupar"]
Choco=["Acandí","Alto Baudó","Atrato","Bafadó","Bahía Solano","Bajo Baudó","Bojayá","Condoto","Cértegui","El Cantónde San Pablo","El Carmen de Atrato","El Carmen de Atrato","El Carmen del Darién","El Litoral de San Juan","Istmina","Juradó","Lloró","Medio Atrato","Medio Baudó","Medio San Juan","Nuquí","Nóvita","Quibdó","Riosucio","Río Iró","Río Quito","San José del palmar","Sipí","Tadó","Unguía","Unión Panamericana"]
Cordoba=["Ayapel","Buenavista","Canalete","Cereté","Chimá","Chinú","Ciénaga de Oro","Cotorra","La Apartada","Los Córdobas","Momil","Montelíbano","Montería","Moñitos","Planeta Rica","Pueblo nuevo","Puerto Escondido","Puerto Libertador","Purísima","Sahagún","San Andrés de Sotavento","San Antero","San Bernardo del Viento","San Carlos","San José de Uré","San Pelayo","Santa Cruz de Lorica","Tierralta","Tuchín" ,"Valencia"] 
Cundinamarca=["Agua de Dios","Albán","Anapoima","Anolaima","Apulo","Arbeláez","Beltrán","Bituima","Bojacá","Cabrera","Cachipay","Cajicá","Caparrapí","Carmen de Carupa","Chaguaní","Chipaque","Choachí","Chocontá","Chía","Cogua","Cota","Cucunubá","Cáqueza","El Colegio","El Peñón","El Rosal","Facatativá","Fosca","Funza","Fusagasugá","Fómeque","Fúquene","Gachalá","Gachancipá","Gachetá","Gama","Girardot","Granada","Guachetá","Guaduas","Guasca","Guataquí","Guatavita","Guayabal de Síquima","Guayabetal","Gutiérrez","Jerusalén","Junín" ,"La Calera","La Mesa","La Palma","La Peña","La Vega","Lenguazaque","Machetá","Madrid","Manta","Medina","Mosquera","Nariño","Nemocón","Nilo","Nimaima","Nocaima","Pacho","Paime","Pandi","Paratebueno","Pasca","Puerto Salgar","Pulí","Quebradanegra","Quetame","Quipile","Ricaurte","San Antonio del Tequendama","San Bernardo","San Cayetano","San Francisco de Sales","San Juan de Rioseco","Sasaima","Sesquilé","Sibaté","Silvania","Simijaca","Soacha","Sopó","Subachoque","Suesca","Supatá","Susa","Sutatausa","Tabio","Tausa","Tena","Tenjo","Tibacuy","Tibirita","Tocaima","Tocancipá","Topaipí","Ubalá","Ubaque","Ubaté","Une","Venecia","Vergara","Vianí","Villagómez","Villapinzon","Villeta","Viotá","Yacopí","Zipacón","Zipaquirá","Útica"]
Guainia=["Barrancominas","Cacahual","Inírida","La Guadalupe","Morichal Nuevo","Pana Pana","Puerto Colombia","San Felipe"]
Guaviare=["Calamar","El Retorno","Miraflores","San José del Guaviare"]
Huila=["Acevedo","Agrado","Aipe","Algeciras","Altamira","Baraya","Campoalegre","Colombia","Elías","Garzón","Gigante","Guadalupe","Hobo","Isnos","La Argentina","La Plata","Neiva","Nátaga","Oporapa","Paicol","Palermo","Palestina","Pital","Pitalito","Rivera","Saladoblanco","San Agustín","Santa María","Suaza","Tarqui","Tello","Teruel","Tesalia","Timaná","Villavieja","Yaguará","Íquira"]
La_Guajira=["Albania","Barrancas","Dibulla","Distracción","El Molino","Fonseca","Hatonuevo","La Jagua del Pilar","Maicao","Manaure","Riohacha","San Juan del Cesar","Uribia","Urumita","Villanueva"	]
Magdalena=["Algarrobo","Aracataca","Ariguaní","Cerro de San Antonio","Chibolo","Ciénaga","Concordia","El Banco","El Piñón","El Retén","Fundación","Guamal","Nueva Granada","Pedraza","Pijiño del Carmen","Pivijay","Plato","Pueblo Viejo","Remolino","Sabanas de San Ángel","Salamina","San Sebastián de Buenavista","Santa Ana","Santa Bárbara de Pinto","Santa Marta","San Zenón","Sitionuevo","Tenerife","Zapayán","Zona Bananera"]
Meta=["Acacías","Barranca de Upía","Cabuyaro","Castilla La Nueva","Cubarral","Cumaral Piedemonte","El Calvario","El Castillo","El Dorado","Fuente de Oro","Granada Ariari","Guamal Piedemonte","La Macarena","La Uribe","Lejanías","Mapiripán","Mesetas Ariari","Puerto Concordia","Puerto Gaitán","Puerto Lleras","Puerto López","Puerto Rico","Restrepo","San Carlos de Guaroa","San Juan de Arama","San Juanito","San Martín","Villavicencio","Vista Hermosa"]
Narino=["Barbacoas","El Charco","Francisco Pizarro","La Tola","Magüí-Payán","Mosquera" ,"Olaya Herrera","Payán","Santa Bárbara ","Tumaco","Aldana","Contadero" ,"Córdoba" ,"Cuaspud" ,"Cumbal" ,"Funes" ,"Guachucal" ,"Gualmatán" ,"Iles","Ipiales","Potosí" ,"puerres","Pupiales" ,"Albán","Arboleda" ,"Belén" ,"Colón","El Rosario","El Tablón de Gómez" ,"La Cruz" ,"La Unión" ,"Leiva" ,"Policarpa" ,"San Bernardo","San Lorenzo","San Pablo" ,"San Pedro de Cartago" ,"Taminango" ,"Buesaco" ,"Chachagüí" ,"Consaca" ,"El Peñol" ,"El Tambo" ,"La Florida","Nariño","San Juan de Pasto","Sandoná" ,"Tangua" ,"Yacuanquer" ,"Ancuya" ,"Cumbitara" ,"Guaitarilla","Imués" ,"La Llanada" ,"Linares" ,"Los Andes-Sotomayor" ,"Mallama" ,"Ospina" ,"Providencia" ,"Ricaurte" ,"Samaniego","Santacruz","Túquerres"]
Norte_de_Santander=["Arboledas","Bochalema","Chitagá","Convención","Cucutilla","Cáchira","Cácota","Cúcuta","Durania","El Carmen","El Tarra","El Zulia","Gramalote","Hacarí","Herrán","La Esperanza","La Playa de Belén","Labateca","Los Patios","Lourdes","Mutiscua","Ocaña","Pamplona","Pamplonita","Puerto Santander","Ragonvalia","Salazar de Las Palmas","San Calixto","San Cayetano","Santiago","Santo Domingo de Silos","Sardinata","Teorama","Tibú","Toledo","Villa Caro","Villa del Rosario","Ábrego"]
Putumayo=["Colón"	,"Mocoa","Orito","Puerto Asís","Puerto Caicedo","Puerto Guzmán","Puerto Leguízamo","San Francisco","San Miguel","Santiago","Sibundoy","Valle del Guamuez","Villagarzón"]
Quindio=["Armenia","Buenavista","Calarcá","Circasia","Córdoba","Filandia","Génova","La Tebaida","Montenegro","Pijao","Quimbaya","Salento"]
Risaralda=["Apía","Balboa","Belén de Umbría","Dosquebradas","Guática","La Celia","La Virginia","Marsella","Mistrató","Pereira","Pueblo Rico","Quinchía","Santa Rosa de Cabal"]
San_Andres_Providencia_y_Santa_Catalina=["San Andrés","Providencia","Santa Catalina","Cayos"]
Santander=["Aguada","Albania","Aratoca","Barbosa","Barichara","Barrancabermeja","Betulia","Bolívar","Bucaramanga","Cabrera","California","Capitanejo","Carcasí","Cepitá","Cerrito","Charalá","Charta","Chima","Chipatá","Cimitarra","Concepción","Confines","Contratación","Coromoro","Curití","El Carmen de Chucurí","El Guacamayo","El Peñón","El Playón","Encino","Enciso","Florián","Floridablanca","Galán","Gámbita","Girón","Guaca","Guadalupe","Guapotá","Guavatá","Güepsa","Hato","Jesús María","Jordán","La Belleza","La Paz","Landázuri","Lebrija","Los Santos","Macaravita","Málaga","Matanza","Mogotes","Molagavita","Ocamonte","Oiba","Onzaga","Palmar","Palmas del Socorro","Páramo","Piedecuesta","Pinchote","Puente Nacional","Puerto Parra","Puerto Wilches","Rionegro","Sabana de Torres","San Andrés","San Benito","San Gil","San Joaquín","San José de Miranda","San Miguel","San Vicente de Chucurí","Santa Bárbara","Santa Helena del Opón","Simacota","Socorro","Suaita","Sucre","Suratá","Tona","Valle de San José","Vélez""Vetas","Villanueva","Zapatoca"]
Sucre=["Guaranda","Majagual","Sucre","Colosó","Morroa","Ovejas","Coveñas","Palmito","San Onofre","Santiago de Tolú","Toluviejo","Buenavista","Corozal","El Roble","Galeras","Los Palmitos","Sampués","San Juan de Betulia","San Pedro","Sincé","Caimito","La Unión","San Benito Abad","San Marcos"]
Tolima=["Alvarado","Anzoátegui","Cajamarca","Coello","Espinal","Flandes","Ibagué","Piedras","Rovira","San Luis","Valle de San Juan","Casabianca","Herveo","Lérida","Líbano","Murillo","Santa Isabel","Venadillo","Villahermosa","Ambalema","Armero","Falan","Fresno","Honda","Mariquita","Palocabildo","Carmen de Apicalá","Cunday","Icononzo","Melgar","Villarrica","Ataco","Chaparral","Coyaima","Natagaima","Ortega","Planadas","Rioblanco","Roncesvalles","San Antonio","Alpujarra","Dolores","Guamo","Prado","Purificación","Saldaña","Suárez"]
Valle_del_Cauca=["Alcalá","Andalucía","Ansermanuevo","Argelia","Bolívar","Buenaventura","Buga","Bugalagrande","Caicedonia","Cali","Darién","Candelaria","Cartago" ,"Dagua","Águila","El Cairo","El Cerrito","El Dovio" ,"Florida","Ginebra","Guacari","Jamundí","La Cumbre","La Unión","La Victoria","Obando","Palmira","Pradera","Restrepo","Riofrío","Roldanillo","San Pedro","Sevilla","Toro","Trujillo" ,"Tuluá","Ulloa","Versalles","Vijes","Yotoco","Yumbo","Zarzal" ]	
Vaupes=["Carurú","Mitú","Pacoa","Papunaua","Taraira","Yavaraté"]
Vichada=["Cumaribo","La Primavera","Puerto Carreño","Santa Rosalía"]

departamentos={"Antioquia" :Antioquia,"Amazonas":Amazonas,"Arauca":Arauca,"Atlántico":Atlantico,"Bolívar":Bolivar,"Boyacá":Boyaca,"Caldas":Caldas,"Caquetá":Caqueta,"Casanare":Casanare,"Cauca":Cauca,"Cesar":Cesar,"Chocó":Choco,"Córdoba":Cordoba,"Cundinamarca":Cundinamarca,"Guainía":Guainia,"Guaviare":Guaviare,"Huila":Huila,"La Guajira":La_Guajira,"Magdalena":Magdalena,"Meta":Meta,"Nariño":Narino,"Norte de Santander":Norte_de_Santander,"Putumayo":Putumayo,"Quindío":Quindio,"Risaralda":Risaralda,"San Andrés,Providencia y Santa Catalina":San_Andres_Providencia_y_Santa_Catalina,"Santander":Santander,"Sucre":Sucre,"Tolima":Tolima,"Valle del Cauca":Valle_del_Cauca,"Vaupés":Vaupes,"Vichada":Vichada }





       

 
